spring:
  datasource:
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      database: loja
      host: 172.17.0.2
  main:
    lazy-initialization: true

server:
  servlet:
    context-path: /api
  port: 8081