spring:
  datasource:
    username: root
    password: root
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  main:
    lazy-initialization: true

server:
  servlet:
    context-path: /api
  port: 8081