spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurante
    username: root
    password: root
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

server:
  servlet:
    context-path: /api
  port: 8083